// Use fragment if you need to wrap multiple children in a parent without creating a wrapper in code, good for flex in multiple children being generated by a map
//import { Fragment } from "react/jsx-runtime";

// import { HomeStyles } from "./home.styles";
// import { useWindowSize } from "../../utilities/functions";

function Home() {
    // const { width } = useWindowSize();

    return(
        <HomeMobile />
    )
}

function HomeMobile() {
    const cards_1 = [
        ["Headshots", "bg-headshot-banner"],
        ["Events", "bg-headshot-banner"],
        ["Milestones", "bg-headshot-banner"]
    ]

    const cards_2 = [
        ["Modelling", "bg-headshot-banner"],
        ["Artwork", "bg-headshot-banner"],
        ["Extras", "bg-headshot-banner"]
    ]

    return (
        <div className="flex flex-col overflow-y-scroll snap-y snap-mandatory h-screen w-screen">
            <section className="snap-start min-h-full bg-banner-image min-w-full bg-center bg-cover">
                <div className="w-full h-full flex flex-col justify-center items-center backdrop-blur-sm">
                    <p className="text-white w-64 drop-shadow-[0_1.2px_1.2px_rgba(0,0,0,0.8)] text-center text-3xl">Gracelyn Johnson</p>
                    <p className="text-white w-48 drop-shadow-[0_1.2px_1.2px_rgba(0,0,0,0.8)] text-center">Photography & Artwork</p>
                </div>
            </section>
            <section className="snap-start min-h-full min-w-full bg-black text-white">
                <h1 className="h-[7vh] w-full text-center leading-[6vh] text-3xl">Galleries</h1>
                <div className="h-[93vh] w-full bg-gradient-to-t from-white flex flex-col justify-evenly">
                    <div className="flex justify-evenly w-full h-full">
                        <div className="flex flex-col justify-around items-center">
                            {cards_1.map((card, index) => (
                                <div className={"h-[25vh] w-[35vw] rounded-md bg-cover bg-no-repeat bg-center relative " + card[1]}>
                                    <p className="w-full text-center text-lg bg-black bg-opacity-35 absolute bottom-0">{card[0]}</p>
                                </div>
                            ))}
                        </div>
                        <div className="flex flex-col justify-around items-center">
                            {cards_2.map((card, index) => (
                                <div className={"h-[25vh] w-[35vw] rounded-md bg-cover bg-no-repeat bg-center relative " + card[1]}>
                                    <p className="w-full text-center text-lg bg-black bg-opacity-35 absolute bottom-0">{card[0]}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}

export default Home;