// Use fragment if you need to wrap multiple children in a parent without creating a wrapper in code, good for flex in multiple children being generated by a map
//import { Fragment } from "react/jsx-runtime";

// import { HomeStyles } from "./home.styles";
// import { useWindowSize } from "../../utilities/functions";

function Home() {
    // const { width } = useWindowSize();

    return(
        <HomeMobile />
    )
}

function HomeMobile() {
    return (
        <div className="flex flex-col overflow-y-scroll snap-y snap-mandatory h-dvh w-dvw">
            <Landing />
            <Blurb />
            <Galleries />
            <Contact />
        </div>
    )
}

function Landing() {
    return (
        <section className="snap-center min-h-full bg-banner-image min-w-full bg-center bg-cover">
            <div className="w-full h-full flex flex-col justify-center items-center backdrop-blur-sm">
                <p className="text-white w-64 drop-shadow-[0_1.2px_1.2px_rgba(0,0,0,0.8)] text-center text-3xl">Gracelyn Johnson</p>
                <p className="text-white w-48 drop-shadow-[0_1.2px_1.2px_rgba(0,0,0,0.8)] text-center">Photography & Artwork</p>
            </div>
        </section>
    )
}

function Blurb() {
    return (
        <section className="snap-center min-h-full min-w-full">
            <div className="w-full h-full flex flex-col justify-between items-center">
                <div className="w-full h-[65dvh] bg-blurb-banner bg-cover bg-center">

                </div>
                <div className="w-full h-[35dvh] border-4 border-black">Here is a small blurb about me.</div>
            </div>
        </section>
    )
}

function Galleries() {
    const cards_1 = [
        ["Headshots", "bg-headshot-banner"],
        ["Events", "bg-headshot-banner"],
        ["Milestones", "bg-headshot-banner"]
    ]

    const cards_2 = [
        ["Modelling", "bg-headshot-banner"],
        ["Artwork", "bg-headshot-banner"],
        ["Extras", "bg-headshot-banner"]
    ]

    return (
        <section className="snap-center min-h-full min-w-full bg-black text-white">
            <h1 className="h-[7dvh] w-full text-center leading-[6vh] text-3xl">Galleries</h1>
            <div className="h-[93dvh] w-full bg-gradient-to-t from-white flex justify-center items-center">
                <div className="flex justify-evenly w-full h-full">
                    <div className="flex flex-col justify-around items-center">
                        {cards_1.map((card) => (
                            <div className={"h-[25vh] w-[40vw] rounded-md bg-cover bg-no-repeat bg-center relative " + card[1]}>
                                <p className="w-full text-center text-lg bg-black bg-opacity-35 absolute bottom-0">{card[0]}</p>
                            </div>
                        ))}
                    </div>
                    <div className="flex flex-col justify-around items-center">
                        {cards_2.map((card) => (
                            <div className={"h-[25vh] w-[40vw] rounded-md bg-cover bg-no-repeat bg-center relative " + card[1]}>
                                <p className="w-full text-center text-lg bg-black bg-opacity-35 absolute bottom-0">{card[0]}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>
    )
}

function Contact() {
    return (
        <section className="snap-center min-h-full min-w-full">
        <form>
            <div className="flex px-4">
                <div>
                    <label>First Name</label>
                    <input type="text" required placeholder="John" className="border-2 border-black" />
                </div>
                <div>
                    <label>Last Name</label>
                    <input type="text" required placeholder="Smith" className="border-2 border-black" />
                </div>
            </div>
            <div className="flex flex-col px-4">
                <label>Email</label>
                <input type="email" required placeholder="johnsmith@domain.com" className="border-2 border-black" />
            </div>
            <div className="flex flex-col px-4">
                <label>Mobile Number</label>
                <input type="number" placeholder="1234567890" className="border-2 border-black" />
            </div>
            <div className="flex flex-col px-4">
                <label>Reason for Contact</label>
                <select required className='border-2 border-black'>
                    <option value="0" disabled selected>Please choose an option</option>
                    <option value="photo">Photography</option>
                    <option value="model">Modelling</option>
                    <option value="art">Artwork</option>
                    <option value="personal">Personal</option>
                </select>
            </div>
            <div className="flex flex-col px-4">
                <label>Details</label>
                <input type="text" required placeholder="Put important information regarding your contact request here." className='border-2 border-black h-36' />
            </div>
            <div className="flex px-4">
                <button type="submit">Submit</button>
            </div>
        </form>
        </section>
    )
}

export default Home;